mod register;
pub use register::*;
mod version;
pub use version::*;
mod login;
pub use login::*;
mod logout;
pub use logout::*;
mod regen;
pub use regen::*;
mod delete;
pub use delete::*;
mod status;
pub use status::*;
mod rename;
pub use rename::*;
mod pwd;
pub use pwd::*;
mod email;
pub use email::*;
mod verify;
pub use verify::*;
